version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "digitalden-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nyy6d4hl4s37"
s3_prefix = "digitalden-backend"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
